name: untitled3
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  polygon_clipper: ^1.0.2
  cloud_firestore:
  url_launcher: ^4.0.3
  firebase_auth: ^0.14.0+5
  flutter_local_notifications: ^0.8.4
  google_sign_in: ^4.0.11
  provider: ^2.0.0+1
  fl_chart: ^0.4.2
  firebase_database: ^3.1.0

  flutter:
    sdk: flutter
  google_maps_flutter: 0.5.21+12
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view:
  expandable:
  http:
  path_provider:
  firebase: ^7.0.0
  firebase_messaging:
  device_info:
  date_format:
  flutter_datetime_picker: ^1.2.8
  js: ^0.6.0
  firebase_storage: ^3.0.8
  flutter_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"


flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true


flutter:


  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-ExtraLight.ttf
        - asset: fonts/Raleway/Raleway-ExtraBold.ttf
        - asset: fonts/Raleway/Raleway-Bold.ttf
        - asset: fonts/Raleway/Raleway-Black.ttf
          weight : 400

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
